### ISSUE TITLE
TTL should be optional

### ISSUE THREAD

**Issue by lassejlv** [samocodes/bun-cache#3]
I'm absolutely in love with this package, but i think the TTL should be optional.

**Comment by ksamirdev** [comment]
Thank you so much for showing love to this package! 🫶

**Comment by lassejlv** [comment]
@samocodes You forgot to update the types def.

**Comment by ksamirdev** [comment]
> @samocodes You forgot to update the types def.

I'm sorry but where the type def is missing? 

Plus the package is moved to `@samocodes/bun-cache`
